name: qiskit.org - lint, test, and build

# run when action is manually triggered
# or when a pull request is made
on: [workflow_dispatch, pull_request]

jobs:
  # job id/key
  lint-test-and-build:
    # job name
    name: Lint, Test, and Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run generate
